 export const data = [
    {id: 1, name: "Algorithm", definition: "A step-by-step procedure for solving a problem or accomplishing a task."},
    {id: 2, name: "Array", definition: "A data structure that contains a group of elements, typically of the same data type."},
    {id: 3, name: "API", definition: "Application Programming Interface; a set of rules that allows different software entities to communicate with each other."},
    {id: 4, name: "Boolean", definition: "A data type that has one of two possible values, usually true or false."},
    {id: 5, name: "Bug", definition: "An error or flaw in software that causes it to produce an incorrect or unexpected result."},
    {id: 6, name: "Class", definition: "A blueprint for creating objects in object-oriented programming, defining their properties and behaviors."},
    {id: 7, name: "Compiler", definition: "A program that translates source code written in a high-level programming language into machine code."},
    {id: 8, name: "Data Structure", definition: "A way of organizing and storing data in a computer so that it can be accessed and modified efficiently."},
    {id: 9, name: "Database", definition: "An organized collection of data, typically stored and accessed electronically."},
    {id: 10, name: "Debugging", definition: "The process of finding and fixing bugs in software."},
    {id: 10, name: "Debugging", definition: "The process of finding and fixing bugs in software."},
    {id: 11, name: "Function", definition: "A block of code designed to perform a particular task, typically taking inputs and returning an output."},
    {id: 12, name: "Git", definition: "A distributed version control system used for tracking changes in source code during software development."},
    {id: 13, name: "IDE", definition: "Integrated Development Environment; a software application that provides comprehensive facilities to programmers for software development."},
    {id: 14, name: "Inheritance", definition: "A feature of object-oriented programming where a new class receives the properties and behaviors of an existing class."},
    {id: 15, name: "JavaScript", definition: "A high-level, interpreted programming language that is commonly used to create interactive effects within web browsers."},
    {id: 16, name: "JSON", definition: "JavaScript Object Notation; a lightweight data interchange format that is easy for humans to read and write and easy for machines to parse and generate."},
    {id: 17, name: "Library", definition: "A collection of precompiled routines that a program can use, usually to save time and effort in coding."},
    {id: 18, name: "Loop", definition: "A control structure that repeats a block of code while a certain condition is true."},
    {id: 19, name: "Machine Learning", definition: "A field of artificial intelligence that uses algorithms to learn from and make predictions or decisions based on data."},
    {id: 20, name: "Method", definition: "A function that is defined within a class and operates on instances of that class."},
    {id: 21, name: "Module", definition: "A file containing Python code, which can define functions, classes, and variables."},
    {id: 22, name: "Node.js", definition: "A JavaScript runtime built on Chrome's V8 engine that allows for server-side scripting."},
    {id: 23, name: "Object", definition: "An instance of a class containing data and methods that operate on that data."},
    {id: 24, name: "Open Source", definition: "Software for which the original source code is made freely available and may be redistributed and modified."},
    {id: 25, name: "Operator", definition: "A symbol that tells the compiler or interpreter to perform a specific mathematical, relational, or logical operation."},
    {id: 26, name: "Parameter", definition: "A variable used in a function definition that receives a value when the function is called."},
    {id: 27, name: "Python", definition: "A high-level, interpreted programming language known for its readability and broad applicability."},
    {id: 28, name: "Recursion", definition: "The process in which a function calls itself directly or indirectly."},
    {id: 29, name: "Repository", definition: "A central location in which data is stored and managed, often used in version control systems."},
    {id: 30, name: "REST", definition: "Representational State Transfer; an architectural style for designing networked applications."},
    {id: 31, name: "Script", definition: "A small program or sequence of instructions that is interpreted or carried out by another program."},
    {id: 32, name: "Server", definition: "A computer or software that provides services to other computers or clients on a network."},
    {id: 33, name: "String", definition: "A sequence of characters, typically used to represent text."},
    {id: 34, name: "Syntax", definition: "The set of rules that defines the combinations of symbols that are considered to be correctly structured programs in a programming language."},
    {id: 35, name: "Tuple", definition: "An ordered collection of elements, which can be of different data types, and is immutable."},
    {id: 36, name: "Variable", definition: "A storage location identified by a memory address and a symbolic name, which contains some known or unknown quantity of information referred to as a value."},
    {id: 37, name: "Version Control", definition: "The management of changes to documents, computer programs, large web sites, and other collections of information."},
    {id: 38, name: "Virtual Machine", definition: "An emulation of a computer system, providing the functionality of a physical computer."},
    {id: 39, name: "Web Framework", definition: "A software framework that is designed to support the development of web applications, including web services, web resources, and web APIs."},
    {id: 40, name: "XML", definition: "Extensible Markup Language; a markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable."},
    {id: 41, name: "YAML", definition: "YAML Ain't Markup Language; a human-readable data serialization standard that can be used in conjunction with all programming languages."},
    {id: 42, name: "Abstraction", definition: "The concept of hiding the complex implementation details and showing only the necessary features of an object."},
    {id: 43, name: "Agile", definition: "A set of principles for software development under which requirements and solutions evolve through the collaborative effort of self-organizing and cross-functional teams."},
    {id: 44, name: "Binary", definition: "A way of representing text or computer processor instructions using the binary number system's two binary digits, 0 and 1."},
    {id: 45, name: "Bit", definition: "The smallest unit of data in a computer, represented by a 0 or a 1."},
    {id: 46, name: "Blockchain", definition: "A growing list of records, called blocks, that are linked using cryptography. Each block contains a cryptographic hash of the previous block, a timestamp, and transaction data."},
    {id: 47, name: "Boolean Logic", definition: "A form of algebra in which all values are reduced to either TRUE or FALSE."},
    {id: 48, name: "Byte", definition: "A unit of digital information that most commonly consists of eight bits."},
    {id: 49, name: "Cache", definition: "A component that stores data so that future requests for that data can be served faster."},
    {id: 50, name: "Closure", definition: "A function that has access to its own scope, the scope of the outer function, and the global scope."},
    {id: 51, name: "Compiler", definition: "A program that translates code from a high-level programming language to a lower-level language to create an executable program."},
    {id: 52, name: "Concurrency", definition: "The ability of different parts or units of a program, algorithm, or problem to be executed out-of-order or in partial order, without affecting the final outcome."},
    {id: 53, name: "Constructor", definition: "A special method of a class or structure in object-oriented programming that initializes a newly created object of that type."},
    {id: 54, name: "Control Flow", definition: "The order in which individual statements, instructions, or function calls of an imperative program are executed or evaluated."},
    {id: 55, name: "CSS", definition: "Cascading Style Sheets; a style sheet language used for describing the presentation of a document written in HTML or XML."},
    {id: 56, name: "Data Mining", definition: "The process of discovering patterns and knowledge from large amounts of data."},
    {id: 57, name: "Data Science", definition: "An interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from data."},
    {id: 58, name: "DOM", definition: "Document Object Model; a cross-platform and language-independent interface that treats an XML or HTML document as a tree structure."},
    {id: 59, name: "Encryption", definition: "The process of encoding information in such a way that only authorized parties can access it."},
    {id: 60, name: "Exception", definition: "An event that occurs during the execution of a program that disrupts the normal flow of instructions."},
    {id: 61, name: "Framework", definition: "A platform for developing software applications. It provides a foundation on which software developers can build programs for a specific platform."},
    {id: 62, name: "Full Stack Developer", definition: "A developer who is capable of working on both the front-end and back-end portions of an application."},
    {id: 63, name: "Garbage Collection", definition: "The process of automatically freeing memory that is no longer in use by the program."},
    {id: 64, name: "Hash Function", definition: "A function that converts an input into a fixed-size string of bytes. The output is typically a 'digest' that is unique to each unique input."},
    {id: 65, name: "HTML", definition: "Hypertext Markup Language; the standard language for creating web pages and web applications."},
    {id: 66, name: "HTTP", definition: "Hypertext Transfer Protocol; the foundation of data communication for the World Wide Web."},
    {id: 67, name: "Interface", definition: "A shared boundary across which two or more separate components of a computer system exchange information."},
    {id: 68, name: "JSON", definition: "JavaScript Object Notation; a lightweight data interchange format that is easy for humans to read and write and easy for machines to parse and generate."},
    {id: 69, name: "Lambda Function", definition: "An anonymous function that is defined using the lambda keyword."},
    {id: 70, name: "Middleware", definition: "Software that acts as a bridge between an operating system or database and applications, especially on a network."},
    {id: 71, name: "NoSQL", definition: "A type of database that provides a mechanism for storage and retrieval of data that is modeled in means other than the tabular relations used in relational databases."},
    {id: 72, name: "OOP", definition: "Object-Oriented Programming; a programming paradigm based on the concept of objects, which contain data and methods."},
    {id: 73, name: "Polymorphism", definition: "The ability to present the same interface for different underlying data types."},
    {id: 74, name: "Protocol", definition: "A set of rules and standards that define a language that devices can use to communicate."},
    {id: 75, name: "Queue", definition: "A collection in which the entities in the collection are kept in order and the principal operations are the addition of entities to the rear terminal position, known as enqueue, and removal of entities from the front terminal position, known as dequeue."},
    {id: 76, name: "Refactoring", definition: "The process of restructuring existing computer code without changing its external behavior."},
    {id: 77, name: "Regex", definition: "Regular Expression; a sequence of characters that forms a search pattern, mainly for use in pattern matching with strings."},
    {id: 78, name: "Repository", definition: "A central location in which data is stored and managed, often used in version control systems."},
    {id: 79, name: "RESTful API", definition: "An application program interface (API) that uses HTTP requests to GET, PUT, POST and DELETE data."},
    {id: 80, name: "Ruby", definition: "A dynamic, open source programming language with a focus on simplicity and productivity."},
    {id: 81, name: "Runtime", definition: "The period during which a computer program is executing."},
    {id: 82, name: "SaaS", definition: "Software as a Service; a software distribution model in which a third-party provider hosts applications and makes them available to customers over the Internet."},
    {id: 83, name: "SQL", definition: "Structured Query Language; a domain-specific language used in programming and designed for managing data held in a relational database management system."},
    {id: 84, name: "Stack", definition: "A collection of elements with two principal operations: push, which adds an element to the collection, and pop, which removes the most recently added element."},
    {id: 85, name: "Static Typing", definition: "A feature of a programming language where type checking is performed during compile-time as opposed to run-time."},
    {id: 86, name: "Token", definition: "A string of characters that represent a unit of information in the syntax of a programming language."},
    {id: 87, name: "UML", definition: "Unified Modeling Language; a standardized modeling language used to specify, visualize, construct, and document the artifacts of a software system."},
    {id: 88, name: "Unit Test", definition: "A software testing method where individual units or components of a software are tested."},
    {id: 89, name: "User Interface", definition: "The space where interactions between humans and machines occur."},
    {id: 90, name: "Version Control", definition: "The management of changes to documents, computer programs, large websites, and other collections of information."},
    {id: 91, name: "Virtual Machine", definition: "An emulation of a computer system, providing the functionality of a physical computer."},
    {id: 92, name: "Web Browser", definition: "A software application for accessing information on the World Wide Web."},
    {id: 93, name: "Web Server", definition: "A computer system that hosts websites and delivers web pages to users over the Internet."},
    {id: 94, name: "WebSocket", definition: "A computer communications protocol, providing full-duplex communication channels over a single TCP connection."},
    {id: 95, name: "Whitespace", definition: "Any character or series of characters that represent horizontal or vertical space in typography."},
    {id: 96, name: "XML", definition: "Extensible Markup Language; a markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable."},
    {id: 97, name: "YAML", definition: "YAML Ain't Markup Language; a human-readable data serialization standard that can be used in conjunction with all programming languages."},
    {id: 98, name: "Zero-Day", definition: "A software vulnerability that is unknown to the parties responsible for patching or fixing the vulnerability."},
    {id: 99, name: "Zigbee", definition: "A specification for a suite of high-level communication protocols using low-power digital radios."},
    {id: 100, name: "Zombie", definition: "A computer that is connected to the Internet and has been compromised by a hacker, computer virus, or Trojan horse."},
    { id: 101, name: "Actor Model", definition: "A conceptual model to deal with concurrent computation by using 'actors' as the universal primitives of concurrent digital computation." },
{ id: 102, name: "ASCII", definition: "American Standard Code for Information Interchange; a character encoding standard for electronic communication." },
{ id: 103, name: "Assembler", definition: "A program that translates assembly language into machine code." },
{ id: 104, name: "Big Data", definition: "A field that treats ways to analyze, systematically extract information from, or otherwise deal with data sets that are too large or complex to be dealt with by traditional data-processing application software." },
{ id: 105, name: "Bitwise Operation", definition: "An operation that operates on binary numerals at the level of their individual bits." },
{ id: 106, name: "Blockchain", definition: "A system in which a record of transactions made in bitcoin or another cryptocurrency are maintained across several computers that are linked in a peer-to-peer network." },
{ id: 107, name: "Bootstrap", definition: "A free and open-source front-end framework for developing websites and web applications." },
{ id: 108, name: "Buffer", definition: "A region of a physical memory storage used to temporarily store data while it is being moved from one place to another." },
{ id: 109, name: "Command Line Interface (CLI)", definition: "A user interface that allows users to interact with a computer by typing commands into a console or terminal." },
{ id: 110, name: "CRUD", definition: "Create, Read, Update, Delete; the four basic functions of persistent storage." },
{ id: 111, name: "Cybersecurity", definition: "The practice of protecting systems, networks, and programs from digital attacks." },
{ id: 112, name: "Data Analytics", definition: "The process of examining data sets to draw conclusions about the information they contain, increasingly with the aid of specialized systems and software." },
{ id: 113, name: "Data Warehouse", definition: "A system used for reporting and data analysis, and is considered a core component of business intelligence." },
{ id: 114, name: "Deployment", definition: "The process by which a software application is installed, configured, and enabled in a specific environment." },
{ id: 115, name: "Distributed Computing", definition: "A field of computer science that studies distributed systems." },
{ id: 116, name: "Docker", definition: "An open platform for developing, shipping, and running applications in containers." },
{ id: 117, name: "Encapsulation", definition: "The bundling of data with the methods that operate on that data, restricting direct access to some of the object's components." },
{ id: 118, name: "ETL", definition: "Extract, Transform, Load; a process in database usage and especially in data warehousing." },
{ id: 119, name: "Front-end Development", definition: "The practice of converting data to a graphical interface, so that users can view and interact with that data." },
{ id: 120, name: "Functional Programming", definition: "A programming paradigm where programs are constructed by applying and composing functions." },
{ id: 121, name: "GIT", definition: "A distributed version-control system for tracking changes in source code during software development." },
{ id: 122, name: "Hadoop", definition: "An open-source framework that allows for the distributed processing of large data sets across clusters of computers using simple programming models." },
{ id: 123, name: "HTTPS", definition: "Hypertext Transfer Protocol Secure; an extension of HTTP used for secure communication over a computer network." },
{ id: 124, name: "Inheritance", definition: "The mechanism in object-oriented programming that allows one class to inherit the properties and methods of another class." },
{ id: 125, name: "Internet of Things (IoT)", definition: "The interconnection via the Internet of computing devices embedded in everyday objects, enabling them to send and receive data." },
{ id: 126, name: "JSON Web Token (JWT)", definition: "A compact, URL-safe means of representing claims to be transferred between two parties." },
{ id: 127, name: "Kanban", definition: "A scheduling system for lean manufacturing and just-in-time manufacturing." },
{ id: 128, name: "Kubernetes", definition: "An open-source container orchestration system for automating computer application deployment, scaling, and management." },
{ id: 129, name: "Legacy System", definition: "An old method, technology, computer system, or application program that is still in use." },
{ id: 130, name: "Microservices", definition: "A software development technique where an application is structured as a collection of loosely coupled services." },
{ id: 131, name: "MongoDB", definition: "A source-available cross-platform document-oriented database program." },
{ id: 132, name: "Neural Network", definition: "A series of algorithms that attempt to recognize underlying relationships in a set of data through a process that mimics the way the human brain operates." },
{ id: 133, name: "NPM", definition: "Node Package Manager; a package manager for the JavaScript programming language." },
{ id: 134, name: "ORM", definition: "Object-Relational Mapping; a technique for converting data between incompatible type systems using object-oriented programming languages." },
{ id: 135, name: "PHP", definition: "A popular general-purpose scripting language that is especially suited to web development." },
{ id: 136, name: "PostgreSQL", definition: "A powerful, open-source object-relational database system." },
{ id: 137, name: "Proxy Server", definition: "A server application or appliance that acts as an intermediary for requests from clients seeking resources from other servers." },
{ id: 138, name: "Refactoring", definition: "The process of restructuring existing computer code without changing its external behavior." },
{ id: 139, name: "Selenium", definition: "An open-source umbrella project for a range of tools and libraries aimed at supporting browser automation." },
{ id: 140, name: "SOAP", definition: "Simple Object Access Protocol; a messaging protocol that allows programs that run on disparate operating systems to communicate using HTTP and XML." },
{ id: 141, name: "Sprint", definition: "A set period of time during which specific work has to be completed and made ready for review in Agile methodology." },
{ id: 142, name: "SSH", definition: "Secure Shell; a cryptographic network protocol for operating network services securely over an unsecured network." },
{ id: 143, name: "SVG", definition: "Scalable Vector Graphics; an XML-based markup language for describing two-dimensional vector graphics." },
{ id: 144, name: "Swagger", definition: "A suite of tools for API developers from SmartBear Software and a former specification upon which the OpenAPI Specification is based." },
{ id: 145, name: "TCP/IP", definition: "Transmission Control Protocol/Internet Protocol; the basic communication language or protocol of the Internet." },
{ id: 146, name: "Test Driven Development (TDD)", definition: "A software development process that relies on the repetition of a very short development cycle: requirements are turned into very specific test cases, then the software is improved to pass the new tests." },
{ id: 147, name: "TypeScript", definition: "An open-source language which builds on JavaScript by adding static type definitions." },
{ id: 148, name: "UUID", definition: "Universally Unique Identifier; a 128-bit number used to uniquely identify information in computer systems." },
{ id: 149, name: "VPN", definition: "Virtual Private Network; extends a private network across a public network and enables users to send and receive data across shared or public networks as if their computing devices were directly connected to the private network." },
{ id: 150, name: "WebAssembly", definition: "A binary instruction format for a stack-based virtual machine, designed as a portable target for the compilation of high-level languages like C, C++, Rust, etc." },
{ id: 151, name: "Abstraction", definition: "The concept of hiding the complex implementation details and showing only the necessary features of an object." },
{ id: 152, name: "Algorithm", definition: "A step-by-step procedure for solving a problem or accomplishing a task." },
{ id: 153, name: "Array", definition: "A data structure that contains a group of elements, typically of the same data type." },
{ id: 154, name: "API", definition: "Application Programming Interface; a set of rules that allows different software entities to communicate with each other." },
{ id: 155, name: "Argument", definition: "A value that is passed to a function when it is called, providing the function with the input it needs to perform its task." },
{ id: 156, name: "Assembly Language", definition: "A low-level programming language that is a symbolic representation of a computer's machine code." },
{ id: 157, name: "Backend", definition: "The server-side of a web application; the part of the application that is not visible to the user and interacts with the server and database." },
{ id: 158, name: "Binary Tree", definition: "A tree data structure in which each node has at most two children, which are referred to as the left child and the right child." },
{ id: 159, name: "Bitwise Operation", definition: "An operation that operates on binary numerals at the level of their individual bits." },
{ id: 160, name: "Bytecode", definition: "An intermediate representation of a program that can be executed by a virtual machine." },
{ id: 161, name: "Callback Function", definition: "A function that is passed as an argument to another function and is executed after a certain event occurs or when a particular condition is fulfilled." },
{ id: 162, name: "CLI", definition: "Command Line Interface; a user interface that allows users to interact with a computer program or operating system by typing commands." },
{ id: 163, name: "Closure", definition: "A function that has access to its own scope, the scope of the outer function, and the global scope." },
{ id: 164, name: "Cloud Computing", definition: "The delivery of computing services over the Internet, including servers, storage, databases, networking, software, analytics, and intelligence." },
{ id: 165, name: "Concurrency", definition: "The ability of different parts or units of a program, algorithm, or problem to be executed out-of-order or in partial order, without affecting the final outcome." },
{ id: 166, name: "Constructor", definition: "A special method of a class or structure in object-oriented programming that initializes a newly created object of that type." },
{ id: 167, name: "Cookie", definition: "A small piece of data sent from a website and stored on the user's computer by the user's web browser while the user is browsing." },
{ id: 168, name: "Cross-platform", definition: "The ability of software to run on more than one type of computer or operating system." },
{ id: 169, name: "CSS", definition: "Cascading Style Sheets; a style sheet language used for describing the presentation of a document written in HTML or XML." },
{ id: 170, name: "Data Mining", definition: "The process of discovering patterns and knowledge from large amounts of data." },
{ id: 171, name: "Database", definition: "An organized collection of data, typically stored and accessed electronically from a computer system." },
{ id: 172, name: "Data Structure", definition: "A way of organizing and storing data in a computer so that it can be accessed and modified efficiently." },
{ id: 173, name: "Debugger", definition: "A tool used by programmers to test and debug code by identifying and correcting errors or bugs." },
{ id: 174, name: "Decorator", definition: "A design pattern in object-oriented programming that allows behavior to be added to individual objects, dynamically, without affecting the behavior of other objects from the same class." },
{ id: 175, name: "Default Value", definition: "A value that is automatically assigned to a variable or function parameter if no other value is specified." },
{ id: 176, name: "Dependency Injection", definition: "A technique whereby one object supplies the dependencies of another object." },
{ id: 177, name: "DNS", definition: "Domain Name System; a hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet or a private network." },
{ id: 178, name: "Documentation", definition: "A set of documents provided with a software product that describes its operation and use." },
{ id: 179, name: "DOM", definition: "Document Object Model; a cross-platform and language-independent interface that treats an XML or HTML document as a tree structure." },
{ id: 180, name: "Dynamic Typing", definition: "A feature of a programming language where variables do not have a fixed data type, and their type can change as the program runs." },
{ id: 181, name: "Encryption", definition: "The process of encoding information in such a way that only authorized parties can access it." },
{ id: 182, name: "Event Handler", definition: "A function or method containing instructions that are executed in response to an event occurring in a GUI or web application." },
{ id: 183, name: "Exception Handling", definition: "The process of responding to the occurrence of exceptions – anomalous or exceptional conditions requiring special processing during program execution." },
{ id: 184, name: "File System", definition: "A method and data structure used by an operating system to manage files on a storage device." },
{ id: 185, name: "Firewall", definition: "A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules." },
{ id: 186, name: "Framework", definition: "A platform for developing software applications. It provides a foundation on which software developers can build programs for a specific platform." },
{ id: 187, name: "Front-end", definition: "The client-side of a web application; the part of the application that the user interacts with directly." },
{ id: 188, name: "FTP", definition: "File Transfer Protocol; a standard network protocol used for transmitting files between a client and server on a computer network." },
{ id: 189, name: "Function", definition: "A block of code designed to perform a particular task, typically taking inputs and returning an output." },
{ id: 190, name: "Garbage Collection", definition: "The process of automatically freeing memory that is no longer in use by the program." },
{ id: 191, name: "GUI", definition: "Graphical User Interface; a type of user interface that allows users to interact with electronic devices using graphical icons and visual indicators." },
{ id: 192, name: "Hash Table", definition: "A data structure that implements an associative array abstract data type, a structure that can map keys to values." },
{ id: 193, name: "Heap", definition: "A region of a computer's memory that is not managed automatically by the operating system, and is used for memory allocation by applications." },
{ id: 194, name: "IDE", definition: "Integrated Development Environment; a software application that provides comprehensive facilities to programmers for software development." },
{ id: 195, name: "Immutable", definition: "An object whose state cannot be modified after it is created." },
{ id: 196, name: "Index", definition: "A data structure that improves the speed of data retrieval operations on a database table at the cost of additional space to maintain the index data structure." },
{ id: 197, name: "Inheritance", definition: "A feature of object-oriented programming where a new class receives the properties and behaviors of an existing class." },
{ id: 198, name: "Instance", definition: "A concrete occurrence of any object, existing usually during the runtime of a computer program." },
{ id: 199, name: "Integer", definition: "A data type that represents whole numbers without fractional components." },
{ id: 200, name: "Interpreted", definition: "A programming language where most of its implementations execute instructions directly and freely, without previously compiling a program into machine-language instructions." },
{ id: 201, name: "SaaS", definition: "Software as a Service; a software distribution model in which a third-party provider hosts applications and makes them available to customers over the Internet." },
{ id: 202, name: "SQL", definition: "Structured Query Language; a domain-specific language used in programming and designed for managing data held in a relational database management system." },
{ id: 203, name: "Stack", definition: "A collection of elements with two principal operations: push, which adds an element to the collection, and pop, which removes the most recently added element." },
{ id: 204, name: "Static Typing", definition: "A feature of a programming language where type checking is performed during compile-time as opposed to run-time." },
{ id: 205, name: "Token", definition: "A string of characters that represent a unit of information in the syntax of a programming language." },
{ id: 206, name: "UML", definition: "Unified Modeling Language; a standardized modeling language used to specify, visualize, construct, and document the artifacts of a software system." },
{ id: 207, name: "Unit Test", definition: "A software testing method where individual units or components of a software are tested." },
{ id: 208, name: "User Interface", definition: "The space where interactions between humans and machines occur." },
{ id: 209, name: "Version Control", definition: "The management of changes to documents, computer programs, large websites, and other collections of information." },
{ id: 210, name: "Virtual Machine", definition: "An emulation of a computer system, providing the functionality of a physical computer." },
{ id: 211, name: "Web Browser", definition: "A software application for accessing information on the World Wide Web." },
{ id: 212, name: "Web Server", definition: "A computer system that hosts websites and delivers web pages to users over the Internet." },
{ id: 213, name: "WebSocket", definition: "A computer communications protocol, providing full-duplex communication channels over a single TCP connection." },
{ id: 214, name: "Whitespace", definition: "Any character or series of characters that represent horizontal or vertical space in typography." },
{ id: 215, name: "XML", definition: "Extensible Markup Language; a markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable." },
{ id: 216, name: "YAML", definition: "YAML Ain't Markup Language; a human-readable data serialization standard that can be used in conjunction with all programming languages." },
{ id: 217, name: "Zero-Day", definition: "A software vulnerability that is unknown to the parties responsible for patching or fixing the vulnerability." },
{ id: 218, name: "Zigbee", definition: "A specification for a suite of high-level communication protocols using low-power digital radios." },
{ id: 219, name: "Zombie", definition: "A computer that is connected to the Internet and has been compromised by a hacker, computer virus, or Trojan horse." },
{ id: 220, name: "Actor Model", definition: "A conceptual model to deal with concurrent computation by using 'actors' as the universal primitives of concurrent digital computation." },
{ id: 221, name: "ASCII", definition: "American Standard Code for Information Interchange; a character encoding standard for electronic communication." },
{ id: 222, name: "Assembler", definition: "A program that translates assembly language into machine code." },
{ id: 223, name: "Big Data", definition: "A field that treats ways to analyze, systematically extract information from, or otherwise deal with data sets that are too large or complex to be dealt with by traditional data-processing application software." },
{ id: 224, name: "Bitwise Operation", definition: "An operation that operates on binary numerals at the level of their individual bits." },
{ id: 225, name: "Blockchain", definition: "A system in which a record of transactions made in bitcoin or another cryptocurrency are maintained across several computers that are linked in a peer-to-peer network." },
{ id: 226, name: "Bootstrap", definition: "A free and open-source front-end framework for developing websites and web applications." },
{ id: 227, name: "Buffer", definition: "A region of a physical memory storage used to temporarily store data while it is being moved from one place to another." },
{ id: 228, name: "Command Line Interface (CLI)", definition: "A user interface that allows users to interact with a computer by typing commands into a console or terminal." },
{ id: 229, name: "Algorithm", definition: "A step-by-step procedure or formula for solving a problem, often implemented as computer code." },
{ id: 230, name: "API (Application Programming Interface)", definition: "A set of rules and protocols that allows different software applications to communicate with each other." },
{ id: 231, name: "Array", definition: "A data structure consisting of a collection of elements, each identified by at least one array index or key." },
{ id: 232, name: "Boolean", definition: "A data type that can have one of two values, usually denoted as true or false." },
{ id: 233, name: "Bug", definition: "An error, flaw, failure, or fault in a computer program or system that causes it to produce an incorrect or unexpected result." },
{ id: 234, name: "Class", definition: "A blueprint for creating objects, providing initial values for state (member variables or properties) and implementations of behavior (member functions or methods)." },
{ id: 235, name: "Closure", definition: "A function that has access to its own scope, even after the function has finished executing." },
{ id: 236, name: "Compiler", definition: "A program that translates code written in one programming language into another language." },
{ id: 237, name: "Constructor", definition: "A special type of method that is used to initialize objects." },
{ id: 238, name: "Database", definition: "A structured collection of data stored electronically in a computer system." },
{ id: 239, name: "Debugging", definition: "The process of finding and fixing errors or bugs in a computer program." },
{ id: 240, name: "Framework", definition: "A platform for developing software applications." },
{ id: 241, name: "Function", definition: "A block of code designed to perform a particular task." },
{ id: 242, name: "GUI (Graphical User Interface)", definition: "A type of user interface that allows users to interact with electronic devices through graphical icons and visual indicators." },
{ id: 243, name: "HTML (Hypertext Markup Language)", definition: "The standard markup language for creating web pages and web applications." },
{ id: 244, name: "IDE (Integrated Development Environment)", definition: "A software application that provides comprehensive facilities to computer programmers for software development." },
{ id: 245, name: "Inheritance", definition: "The mechanism in object-oriented programming where one class acquires the properties and behaviors of another class." },
{ id: 246, name: "Interface", definition: "A boundary across which two independent systems meet and act on or communicate with each other." },
{ id: 247, name: "Library", definition: "A collection of precompiled routines that a program can use." },
{ id: 248, name: "Loop", definition: "A sequence of instructions that is continually repeated until a certain condition is reached." },
{ id: 249, name: "Method", definition: "A function associated with an object, defining the behavior of the objects of a class." },
{ id: 250, name: "Object", definition: "A self-contained entity that consists of both data and procedures to manipulate the data." },
{ id: 251, name: "Operator", definition: "A symbol that represents an operation to be performed with operands." },
{ id: 252, name: "Recursion", definition: "A programming technique where a function calls itself in its own definition." },
{ id: 253, name: "Scripting", definition: "The process of writing scripts, which are typically interpreted rather than compiled." },
{ id: 254, name: "SQL (Structured Query Language)", definition: "A domain-specific language used in programming and designed for managing data held in a relational database management system." },
{ id: 255, name: "Syntax", definition: "The set of rules that defines the combinations of symbols that are considered to be correctly structured statements or expressions in a programming language." },
{ id: 256, name: "Thread", definition: "The smallest sequence of programmed instructions that can be managed independently by a scheduler in an operating system." },
{ id: 257, name: "Variable", definition: "A symbolic name that is associated with a value and whose associated value may be changed." }
]


